### ISSUE TITLE
Copy file remote/remote

### ISSUE THREAD

**Issue by cliviu** [hierynomus/smbj#174]
Hi,
  is there any simple Api call to copy a file from remote to remote ? 
   Or I should use the Input/Output Streams of the opened files to copy the files from remote to remote ?
Thanks !

**Comment by cliviu** [comment]
What is the best place to ask questions about the  smbj  API ? They are not really like issues, not defects but I will need some shortcuts to get easier so some results. For example , how can I read the FileAttributes  of an existing file ? Thanks

**Comment by mtamassia** [comment]
@cliviu this is probably a good spot to ask the question. As far as I know there are no exposed methods / APIs but you can easily code it.  Please take a look at the code from Files.copy method and see if you can use it for your use case. 

https://github.com/hierynomus/smbj/blob/master/src/main/java/com/hierynomus/smbj/utils/SmbFiles.java

You can easily do it using In/Out Streams, as you suggested.

**Comment by ecki** [comment]
SMB also supports server side copy, a client API for that would be great: https://wiki.samba.org/index.php/Server-Side_Copy

**Comment by gidravlic** [comment]
Hi!
While smbj don't support server side copy i use:
```java
    /**
     *
     * @param remoteSourcePath
     * @param remoteDestinationPath
     */
    public void сopy(String remoteSourcePath, String remoteDestinationPath) {
        try (InputStream stream = readBytes(transformPath(remoteSourcePath))) {
            write(transformPath(remoteDestinationPath), stream);
        } catch (IOException | SMBApiException ex) {
            log.error("Error while copy file {}", remoteSourcePath, ex);
        }
    }
    /**
     *
     * @param remotePath
     * @param is
     * @throws IOException
     * @throws SMBApiException
     */
    public void write(final String remotePath, InputStream is) throws IOException, SMBApiException {
        try (File file = diskShare.openFile(transformPath(remotePath), EnumSet.of(AccessMask.GENERIC_WRITE), null, SMB2ShareAccess.ALL, FILE_OVERWRITE_IF, null)) {
            file.write(new InputStreamByteChunkProvider(is));
        }
    }
    private String transformPath(String path) {
        return path.replace("/", "\\");
    }
    private InputStream readBytes(String remotePath) throws IOException, SMBApiException {
        ByteArrayInputStream byteStream;
        try (File file = diskShare.openFile(transformPath(remotePath), EnumSet.of(AccessMask.GENERIC_READ), null, SMB2ShareAccess.ALL, FILE_OPEN, null)) {
            byteStream = new ByteArrayInputStream(IOUtil.getBytes(file.getInputStream()));
        }
        return byteStream;
    }
```
IOUtil.getBytes - method wich get all stream bytes from JDK 9
```java
    public static byte[] getBytes(InputStream stream) throws IOException {
        return readFully(stream, -1, true);
    }

    static byte[] readFully(InputStream is, int length, boolean readAll) throws IOException {
        byte[] output = {};
        if (length == -1) {
            length = Integer.MAX_VALUE;
        }
        int pos = 0;
        while (pos < length) {
            int bytesToRead;
            if (pos >= output.length) { // Only expand when there's no room
                bytesToRead = Math.min(length - pos, output.length + 1024);
                if (output.length < pos + bytesToRead) {
                    output = Arrays.copyOf(output, pos + bytesToRead);
                }
            } else {
                bytesToRead = output.length - pos;
            }
            int cc = is.read(output, pos, bytesToRead);
            if (cc < 0) {
                if (readAll && length != Integer.MAX_VALUE) {
                    throw new EOFException("Detect premature EOF");
                } else {
                    if (output.length != pos) {
                        output = Arrays.copyOf(output, pos);
                    }
                    break;
                }
            }
            pos += cc;
        }
        return output;
    }
```

**Comment by cliviu** [comment]
Great, thank you all !

**Comment by pepijnve** [comment]
@cliviu do you want to copy from one server to another or between directories on the same server? The server-side copy functionality that @ecki mentioned is only applicable for the latter. For the former reading from one file and writing to another (as @gidravlic showed) is the best you can do. Note that his code, while technically correct, will have issues with large files due to reading the entire input in memory before writing to the target. A typical copy loop looks something like this
```
public static void copyFile(File source, File destination) throws IOException {
    byte[] buffer = new byte[<some buffer size>];
    try(InputStream in = source.getInputStream()) {
        try(OutputStream out = destination.getOutputStream()) {
            int bytesRead;
            while((bytesRead = in.read(buffer)) != -1) {
                out.write(buffer, 0, bytesRead);
            }
        }
    }
}
```
The optimal size of the buffer is application and server dependent. You need to balance how much memory you want to allocate for this and what size of read and write buffer the source and target servers support. `NegotiatedProtocol#getMaxReadSize` and `NegotiatedProtocol#getMaxWriteSize` will tell you what the largest buffer size is that a server supports for reads and writes respectively. If you try to use a buffer size that is larger than that, smbj will have to issue multiple requests itself.

As for server side copy, while smbj doesn't implement it yet it is possible to implement it on top of it yourself if you need it. At the SMB protocol level server side copy is done using ioctl requests on files.
First you need to request a resume key for the source file by sending the `FSCTL_SRV_REQUEST_RESUME_KEY` (0x00140078) ioctl with an empty data buffer. That should get you an ioctl response with an [SRV_REQUEST_RESUME_KEY](https://msdn.microsoft.com/en-us/library/cc246804.aspx) struct in the data buffer.
Once you have that resume key you can send `FSCTL_SRV_COPYCHUNK` (0x001440F2) or `FSCTL_SRV_COPYCHUNK_WRITE` (0x001480F2) ioctl request to the destination file with a [SRV_COPYCHUNK_COPY](https://msdn.microsoft.com/en-us/library/cc246547.aspx) struct in the databuffer. According to the spec you should use `FSCTL_SRV_COPYCHUNK` when the target file was opened with `FILE_READ_DATA` and `FILE_WRITE_DATA` and use `FSCTL_SRV_COPYCHUNK_WRITE` when it was opened with only `FILE_WRITE_DATA`.
Note that this is all theoretical based on the specs; I haven't tried this myself yet 😄
As you can see this is quite a bit more low-level than your average library user would like to go, but it is feasible. Ideally smbj would support this out of the box. Might be a good idea to make a separate feature request for this if people think this would be useful.

**Comment by cliviu** [comment]
Hi @pepijnve . For the moment I have to copy between directories of the same server. It works well with the streams approach that you have mentioned, I have a buffer size of 8000 bytes. Thanks !

**Comment by pepijnve** [comment]
I created #175 with the explanation above to track server-side copy support.

**Comment by bamlASD** [comment]
HI I am trying to implement @gidravlic 's solution above but I am running into a few errors. The first is in the write function when trying to fill the file variable. I am receiving the following error when using the FILE_OVERWRITE_IF attribute, "FILE_OVERWRITE_IF cannot be resolved to a variable".  I do not have any issues with FILE_OPEN in the readBytes function. 

Also will IOUtil.getBytes only work with JDK9? We are using 8.

**Comment by hierynomus** [comment]
@bamlASD The first probably means you're missing an import. `IOUtil,.getBytes` is JDK9 only indeed.

**Comment by gidravlic** [comment]
@hierynomus You are right. Only getBytes function from JDK9

**Comment by bamlASD** [comment]
I am able to copy 1 file from server to server using gidravlic's example above, but how can I copy a whole folder from server to server? The Directory object does not support getInputStream(). Also we are on JDK8 so I am using IOUtils.toByteArray as opposed to IOUtil.getBytes in the example above Thanks.

**Comment by pepijnve** [comment]
That's an operation that doesn't exist at the protocol level. You need to do that yourself by recursively listing the source directory and copying each directory/file/... you encounter to the destination.

**Comment by hierynomus** [comment]
It isn't too hard to add a method to the Directory class that does this.

**Comment by bamlASD** [comment]
Okay, so I can copy the entire contents of once folder from source to the folder on the target! My issue is how can I get a list of folder names? If I am connected to a share I have no idea if there are other folders I need to access and connect to then copy their contents. 

Example A on the home page "for (FileIdBothDirectoryInformation f : share.list(sourceSharePath, "*.*"))....." only list the files in the folder and not any other potential folders.

**Comment by pepijnve** [comment]
You need to apply the folder copy logic recursively. Something like this (in pseudo-code):

```
folders = set of folders to copy
while (!folders.isEmpty) {
  folder = folders.removeFirst();
  for (child in folder.list) {
    if (child is a directory) {
      folders.add(folder + "\" + child);
      createDirectoryOnTarget(child);
    } else {
      copyToTarget(child);
    }
  }
}
```
