### ISSUE TITLE
Disabling signatures when guest/anonymous

### ISSUE THREAD

**Issue by tosmun-r7** [hierynomus/smbj#196]
We've had an ongoing discussion here around guest sessions: https://github.com/hierynomus/smbj/issues/184#issuecomment-329306762

The conclusion I've come to is that SMB does not allow for signing when the session is resolved to be a guest or anonymous: https://blogs.msdn.microsoft.com/openspecification/2017/05/26/smb-2-and-smb-3-security-in-windows-10-the-anatomy-of-signing-and-cryptographic-keys/
>
> To sign a message, the first two prerequisites are:
> • Existence of the signing key: SessionId field has a non-zero value, otherwise there would be no possible signing key. The exception is a guest or anonymous session, which does not have a signing key even there’s a SessionId.
> • Signing requirement: SessionId requires signing, i.e. its Session.SigningRequired is equal to TRUE as outlined previously.

Since from the perspective of an smbj user, I won't know that the session is guest or anonymous until the `Session` is returned to me. I've supported `SmbConfig.withSigningRequired` by checking if the returned Session is a guest or anonymous after it is returned, disabling signing if it is, and then reconnecting.

I feel like smbj could support this without forcing the reconnect from the user, perhaps by checking after it has completed the `SMB2_SESSION_SETUP` request and choosing not to calculate a secret key.  What do you think @hierynomus ?

**Comment by hierynomus** [comment]
I'm actually of a somewhat different mind here. The reason being that I don't like it if a library "does magic stuff" 😉.

As such I think the following behaviour is better:
- `SmbConfig.withSigningRequired(true)` has been set and user is authenticating with Guest/Anonymous --> Throw an exception that signing cannot be enabled for guest/anon access
- No signing has been required --> correctly handle the absence of a signing key when guest/anon access is present

Magic "reconnects" belong outside of the library, I can imagine a ton of use-cases where implementors would not want to have this kind of automagic behaviour.

**Comment by tosmun-r7** [comment]
I agree. Deterministic behavior is always preferred.

I also agree with throwing a specific exception instead of returning the session is the best approach from smbj side. Currently it will fail the signature validation when we attempt to use it.

Thanks for the input!

**Comment by hierynomus** [comment]
After a bit of digging, I found the relevant sections in MS-SMB2:

**3.2.5.3.1 Handling a New Authentication**
[...]
- If the global setting _RequireMessageSigning_ is set to TRUE or **Connection.RequireSigning** is set to TRUE then **Session.SigningRequired** MUST be set to TRUE, otherwise **Session.SigningRequired** MUST be set to FALSE.
- If the security subsystem indicates that the session was established by an anonymous user, **Session.SigningRequired** MUST be set to FALSE.
- If the SMB2_SESSION_FLAG_IS_GUEST bit is set in the **SessionFlags** field of the SMB2 SESSION_SETUP Response and if **Session.SigningRequired** is TRUE, this indicates a SESSION_SETUP failure and the connection MUST be terminated. If the SMB2_SESSION_FLAG_IS_GUEST bit is set in the **SessionFlags** field of the SMB2 SESSION_SETUP Response and if **RequireMessageSigning** is FALSE, **Session.SigningRequired** MUST be set to FALSE.
- If **Connection.Dialect** belongs to the SMB 3.x dialect family and if the SMB2_SESSION_FLAG_ENCRYPT_DATA bit is set in the **SessionFlags** field of the SMB2 SESSION_SETUP Response, **Session.EncryptData** MUST be set to TRUE, and **Session.SigningRequired** MUST be set to FALSE.
