### ISSUE TITLE
[Improvement] Lower amount of threads created in case of intensive messaging

### ISSUE THREAD

**Issue by ndimitry** [hierynomus/smbj#203]
Each (or at least many) request is executed in a Future object, in a separate thread. This results in high number of active threads and a lot of threads creation/closing operations. Maybe there is reason to use some pool for the threads and reuse them?

**Comment by pepijnve** [comment]
A Future does not necessarily correspond to a thread. Every SMB client connection spawns a single thread for read purposes. Every request is written to the socket on the calling thread. Since the response is not immediately available a Future is returned. These futures are tracked internally in an in-flight requests map. When the reader thread reads the response for a particular request, it looks up the corresponding future and sets its value to the response object.

**Comment by hierynomus** [comment]
thanks @pepijnve :) Saves me from typing something similar.

**Comment by ndimitry** [comment]
Thanks for info!
Then this might be also our project issue. Let's see (:

**Comment by gidravlic** [comment]
@ndimitry Close to the [issue 158](https://github.com/hierynomus/smbj/issues/158). Right now i'm monitoring how my project work in Payara 4.2 application server. While problems I don't observe.

**Comment by ndimitry** [comment]
@gidravlic Actually all works fast and fine for me so far, but yes, after 1.5 hours of work I see more than 200k threads were active (only 250-750 work in parallel, so there are many created/stopped threads).
Yes, I extensively read/write data from the share... (:

**Comment by hierynomus** [comment]
Which names have these threads? Where do they come from?
Are you re-connecting a lot? Are you forgetting to close connections/sessions?

**Comment by ndimitry** [comment]
I will check this further on.
I use only one connection and one session and try to keep it until any exception occurs, only in this case I reconnect. Maybe it would be better to use some more sessions/connections to boost the performance (at some day...).
So there is quite a chance this is our issue (we are using thread pools, maybe we configured it not properly), not an smbj one.
