### ISSUE TITLE
Is there other option than user/password for authenticate?

### ISSUE THREAD

**Issue by brielga** [hierynomus/smbj#221]
So, my problem is that I'm trying to avoid username and password in my project properties.
Are there other options for atuhentication?

**Comment by pepijnve** [comment]
Kerberos authentication using the [GSSAuthenticationContext](https://github.com/hierynomus/smbj/blob/master/src/main/java/com/hierynomus/smbj/auth/GSSAuthenticationContext.java). Not something I have much experience with myself in practice I'm afraid, so I can't help you much more than that.

**Comment by chrisgch** [comment]
Where is Kerberos authentication used? I'm using smbj in my free Android app, and had to remove all GSSApi related classes because org.ietf.jgss and com.sun.security.jgss isn't available on Android. Normal Windows and Linux servers don't seem to use Kerberos/GSS?

**Comment by pepijnve** [comment]
Kerberos is used quite extensively in Windows. Not really the best reference, but have a look at https://en.wikipedia.org/wiki/Kerberos_(protocol)#Microsoft_Windows.

Anyway, this might not be what your looking for. What kind of solution did you have in mind?

**Comment by chrisgch** [comment]
Just normal SMB share access, mainly to Windows 10 where SMB1 is now disabled on new installations. So far I have used the jcifs library, but it is SMB1 only. smbj is working great on Android even with Kerberos removed, that's why I'm wondering where it is used. Maybe only in corporate environments (e.g. active directory)?

**Comment by ecki** [comment]
Yes, if the domain is set up for it the Windows Integrated Authentication uses Kerberos. IWA uses SPNEGO to allow initiators and acceptors to negotiate either Kerberos or NTLMSSP.

**Comment by chrisgch** [comment]
Unfortunately I have to pass, I don't know enough about Kerberos negotiation to get this to work. As I understand it, smbj does not request a Kerberos ticket from the KDC (Key Distribution Center). It expects a Kerberos ticket as the last parameter to GSSAuthenticationContext. It then uses that ticket for logging into the SMB server. Since Android isn't logged into a domain (contrary to a Windows client), my app would have to request the Kerberos ticket by itself. Since my app is mainly targeted at consumers, it's not really worth the troubles to get this to work.

**Comment by pepijnve** [comment]
> Since my app is mainly targeted at consumers, it's not really worth the troubles to get this to work.

If that's the case, can't you prompt for the username/password? Something like this

1. authenticate using the anonymous context
2. if that fails, prompt for username/password
3. create a username/password authentication context and authenticate again

**Comment by chrisgch** [comment]
Yes, that's exactly what I'm doing now, and it's working great! I create an AuthenticationContext and then call authenticate(). However, authenticate only supports NTLM/NTLMv2 logins. GSSApi is only used when creating a GSSAuthenticationContext. But this needs a GSSCredential as the last parameter, so it requires that you are already connected to the domain in order to use GSS/Kerberos. That's why I have removed all GSS code from my ap since it's never used with AuthenticationContext.

**Comment by pepijnve** [comment]
If you would want to go the Kerberos route (but honestly I don't see why you would bother with it if you have something working with NTLM) https://github.com/cconlon/kerberos-android-ndk looks like something that might be a good example to start from.
You don't necessarily have to be joined to the domain to use this, but you do need to ensure that the clocks of the KDC (the domain controller) and the client devices are in sync. The Kerberos protocol requires synced clocks in order for it to work correctly.

**Comment by hierynomus** [comment]
@brielga Can this be closed? I think the question has been answered. If you think otherwise, please provide some more input.

**Comment by brielga** [comment]
@hierynomus Ok.
