### ISSUE TITLE
does smbj support smb3??

### ISSUE THREAD

**Issue by munirajtomar** [hierynomus/smbj#287]
we are going to use content-fetch and delete action on remote files from a smb3 devices. Still there is an open questions around smbj support for SMB3. Can you guys please confirm. Thanks in advance.

**Comment by hierynomus** [comment]
Hi muniraj, smb3 support is not done yet. Are you sure that what you want is not supported in smb2?

**Comment by munirajtomar** [comment]
Hi , thanks for your quick response. Yes , we are looking for a SMB client library which supports all SMB 1/2/3 version. Currently we are using smbj for SMB2 devices. Any leads for a library which supports SMB3 also would be appreciated. Thanks in advance.

**Comment by hierynomus** [comment]
Smb3 is on the roadmap, however my bandwidth is very limited at this time.

Op 30 jan. 2018 11:06 a.m. schreef "Muniraj Singh Tomar" <
notifications@github.com>:

**Comment by munirajtomar** [comment]
thanks for the clarification @hierynomus .

**Comment by violinvicky** [comment]
Hello, Any update on availability of SMB V3? Thank you in advance.

**Comment by ecki** [comment]
Just a comment, unlike SMB 1 -> SMB 2 the "must support SMB 3" is not that important as SMB 3 as I understand it is not a incompatible protocol, only extensions. So you basically use SMB2 with SMB3 functions. So the question is which SMB3 function you would need. Most likely feature is multi-channel or end to end encryption or the new signing (the later would probably be a minimum requirment to call it SMB3?)

**Comment by deepakggn** [comment]
Hello @hierynomus ,great work on the smbj, everything is working for my setup! Is SMB3 supported now by smbj? if not, then when would it be available ?

**Comment by oranoran** [comment]
Hi @hierynomus, nice to see the progress of this project!

So, it looks like SMB3 isn't supported yet. It's a major feature and with limited resources and SMB2 working so awesomely, understandably it's hard to make this come together.
My interest in SMB3 (and probably other folks' interest too) is about making use of SMB3's more advanced security features, especially encryption.

If there was some kind of roadmap of where SMB3 support stands right now, maybe I could help close some of the gaps in the implementation. Could you maybe try to point out what the gaps are? I.e., what's the minimal set of code still needed in order to get some initial support out the door?

Thanks!

**Comment by niravravalhighq** [comment]
Hi @hierynomus 
Great project works and works great with SMB2.x protocol. Now as I see this ticket conversion, I am also in need to migrate to SMB 3 protocol. Does that support added in SMBJ 0.9.1 or still in process?
Thanks.

**Comment by ecki** [comment]
@niravravalhighq Can you comment which SMB 3 Features you would need to use? It is always helpful for priorisation (and I think none are yet in smbj)

**Comment by pepijnve** [comment]
The only protocol level changes that SMBJ will need to support are the mandatory encryption related ones. The other new features in SMB 3 are all performance optimisation related and are not essential for basic SMB 3 compatibility.

Azure Files is an SMB 3 only service; perhaps that could be a good candidate for compatibility testing.

**Comment by hierynomus** [comment]
Merged to master with #455
