### ISSUE TITLE
Broadcast address

### ISSUE THREAD

**Issue by CraigNSt** [hierynomus/smbj#299]
Hi,

How do we set the broadcast address?

Thanks,
Craig

**Comment by pepijnve** [comment]
You're going to have to be a bit more specific than that @CraigNSt. What are you trying to do exactly?

**Comment by hierynomus** [comment]
Not sure what you mean? This is an smb client, it does not use the netbios broadcast address to discover an smb server.

**Comment by CraigNSt** [comment]
Okay, I'm trying to use it on android.  I have been using the jcifs library but it only implements SMB1 which is not supported by default on windows 10.  On android, when trying to connect to a server with a server name you get a "java.net.UnknownHostException" unless you set the broadcast address first.  I was able to do that using the jcifs library.

**Comment by ecki** [comment]
It does not support netbios broadcast. Your jvm must be able to resolve the hostname (which is not a big issue since modern windows networks should all provide stable DNS). You can type the address instead (I think android won’t do mDNS).

Maybe it would make sense to add a SockAddr variant to SMBClient.connect so the client can use other resolvers to pass a address along, But I guess that might break with DFS/Redirects.

**Comment by CraigNSt** [comment]
Thanks for your response.  I suspected this would be the answer as I had gone through your code before asking and hadn't seen an easy way to do it.  I will use a separate NetBIOS component to find the servers IP and then use that to connect.
