### ISSUE TITLE
Question: How to use DiskShare ?

### ISSUE THREAD

**Issue by cliviu** [hierynomus/smbj#300]
Is the DiskShare class thread safe ?  How is the standard way for using it ? Can a single instance of a DiskShare be used by multiple threads to perform several operations ? 

Currently I'm getting a new Session from the Connection and calling connectShare to get a new DiskShare instance for each operation (which I also close after each operation)
If I try to reuse the DiskShare instance between more threads nothing works as it should.
  
Can somebody please advice which is the way to go here  ? 

Thanks !

**Comment by pepijnve** [comment]
DiskShare itself should be fine to use from multiple threads. I just checked the code and it looks like the internal DFS resolver is not thread safe though. Is DFS involved? If so, could you check if your multi-threaded, DiskShare sharing, code is working correctly with a non-DFS server?

If the DFS resolver turns out to be the problem, then that's a bug that will need to be resolved.
As another test, you could try 'fixing' this yourself in your code by creating your SMBClient instance like this
```
new SMBClient() {
    @Override
    public PathResolver getPathResolver() {
        final PathResolver pathResolver = super.getPathResolver();
        return new PathResolver() {
            @Override
            public SmbPath resolve(Session session, SMB2Packet responsePacket, SmbPath smbPath) throws PathResolveException {
                synchronized (pathResolver) {
                    return pathResolver.resolve(session, responsePacket, smbPath);
                }
            }

            @Override
            public Set<NtStatus> handledStates() {
                return pathResolver.handledStates();
            }
        };
    }
};
```

**Comment by cliviu** [comment]
Hi, thanks for your hack ! It may be useful but I could not prove it because I have found the problem somewhere else in my code. It was some resource not being closed which was causing the problems. 
Thanks !

**Comment by hierynomus** [comment]
Great to hear it wasn't the lib 😉

**Comment by pepijnve** [comment]
@hierynomus I rereviewed the DFS resolver code. Most of it is fine indeed. I've create PR #301 with some minor thread safety improvements.

**Comment by hierynomus** [comment]
Thanks @pepijnve. I'll review it later.
