### ISSUE TITLE
How can we filter out the files from directory according to ChangeTime() 

### ISSUE THREAD

**Issue by rahulgangarde** [hierynomus/smbj#308]
like in java io file we can filter out the directory by applying file filters. Eg below link 

http://www.avajava.com/tutorials/lessons/how-do-i-filter-files-based-on-their-last-modified-dates.html

Also in smb 1.0 **jcifs** we have SmbFileFilter. SO is there any support like same in the smbj?

thanks in advance

**Comment by pepijnve** [comment]
Server side filtering is not part of the SMB protocol, so the library doesn't make this higher level functionality available. You can do this manually though. Code is essentially the same as what you linked to:

```
Directory dir = ...;
List<FileIdBothDirectoryInformation> iterator = dir.list();
for (FileIdBothDirectoryInformation child : iterator) {
     FileTime lastMod = child.getLastWriteTime();
    System.out.println("File: " + child.getFileName() + ", Date: " + lastMod + "");
}
```

**Comment by rahulgangarde** [comment]
yes you are right , but in my case actually i am looking out the functionality like only fetch files which are added/modified after given time

**Comment by pepijnve** [comment]
> As I understand smbj support file mask.

That's correct. That parameter gets mapped directly to the file name parameter of the underlying [QUERY_DIRECTORY](https://msdn.microsoft.com/en-us/library/cc246551.aspx) request.

This is the one type of filter that can actually be sent to the server. Note that the specification is very vague on how this filter actually gets applied. All it says is '[the server MUST invoke the query directory procedure from the underlying object store in an implementation-specific manner](https://msdn.microsoft.com/en-us/library/cc246746.aspx)'.

Any other kind of filtering needs to be done on the client side.

BTW, for large directories you should use the `iterator()` or `iterator(informationClass)` method instead of `list()`. These will lazily retrieve chunks of directory content instead of loading everything in memory up front.

**Comment by rahulgangarde** [comment]
thanks for iterator() related suggestion . I will do client side filtering for my requirement.

**Comment by hierynomus** [comment]
Closing this issue as it has been answered.
