### ISSUE TITLE
How to get an Inputstream?

### ISSUE THREAD

**Issue by fiasko131** [hierynomus/smbj#345]
Hello,

could you give me some explanations (I do not find any elements in the readme) on how to get the inputstream of a given file:

I tested with this code snippet:
````java
Set<SMB2ShareAccess> s = new HashSet<>();
s.add(SMB2ShareAccess.FILE_SHARE_WRITE);
s.add(SMB2ShareAccess.FILE_SHARE_READ);
File remoteSmbjFile =activity.mCurrentDiskShare.openFile(activity.mCurrentSmb2Path+"\\"+item.fileName+"."+item.getExt()
                                                            , EnumSet.of(AccessMask.GENERIC_ALL)
                                                            , null, s, null, null);
String pathDest=Environment.getExternalStorageDirectory().getPath()+"/"+item.fileName+"."+item.getExt();

java.io.File dest = new java.io.File(pathDest);
 if (!dest.exists()) 
try {
         dest.createNewFile();
      } catch (IOException e) {
          e.printStackTrace();
      }
InputStream is = remoteSmbjFile.getInputStream();
Log.i("smbstream",String.valueOf(is));
try {
       OutputStream os = new FileOutputStream(dest);
       byte[] buffer = new byte[1024];
                                               
        try {
               int bytesRead;
               int totalBytesCount =0;
               while ((bytesRead = is.read(buffer)) != -1) {
                           os.write(buffer, 0, bytesRead);
                           totalBytesCount += bytesRead;
                           Log.i("smbstream",String.valueOf(totalBytesCount));

                }
          } catch (IOException e) {
                     e.printStackTrace();
          }
 } catch (FileNotFoundException e) {
           e.printStackTrace();
 }
Log.i("smbstream","success");                                           
                                            
                                          
````

The inputstream is not null, I have no warnings, but I do not get any bytes ...

On the other hand, on the second attempt:

> com.hierynomus.mssmb2.SMBApiException: STATUS_SHARING_VIOLATION (0xc0000043): Create failed for \\192.168.1.96\Users\steph\Music\testOgg.ogg

I'm not sure I understand what I'm doing ... :))

**Comment by pepijnve** [comment]
`STATUS_SHARING_VIOLATION` means you're trying to open a file that had already been opened and the sharing mode you specified does not allow multiple opens. Have a look at the `dwShareMode` documentation at https://docs.microsoft.com/en-us/windows/desktop/api/fileapi/nf-fileapi-createfilea for the details.

From your code the quick solution is to pass `SMB2ShareAccess.ALL` as the `shareAccesses` parameter value to `DiskShare#openFile`. Whether that's appropriate for your application or not is up to you to determine.

**Comment by fiasko131** [comment]
@pepijnve 
I have already tried with:
````java
Set<SMB2ShareAccess> s = new HashSet<>();
s.add(SMB2ShareAccess.ALL.iterator().next());
````
Without success.
What is curious is that the problem of violation comes when I try a second time with the same file ???
And not the first time?

**Comment by pepijnve** [comment]
> Set<SMB2ShareAccess> s = new HashSet<>();
> s.add(SMB2ShareAccess.ALL.iterator().next());

That doesn't make sense. With that bit of code you're passing the first value in ALL. Just pass SMB2ShareAccess.ALL directly.

> What is curious is that the problem of violation comes when I try a second time with the same file ???

That's expected. Your code is not closing the file handle explicitly so from the server's perspective you still have it open. You're specifying the READ and WRITE share mode, but not the DELETE mode. But when opening the file you're asking for `GENERIC_ALL` access which includes permission to delete the file. Hence you get a sharing violation.

Adding `SMB2ShareAccess.FILE_SHARE_DELETE` to `s` or just using `SMB2ShareAccess.ALL` (effectively the same thing) should resolve that.
Alternatively, if you only want to read the file, use `GENERIC_READ` instead of `GENERIC_ALL`. In that case `SMB2ShareAccess.FILE_SHARE_READ` should be sufficient.

**Comment by pepijnve** [comment]
> s.add(SMB2ShareAccess.ALL);

Either call `s.addAll(SMB2ShareAccess.ALL);` or do `Set<SMB2ShareAccess> s = SMB2ShareAccess.ALL;` indeed.

**Comment by fiasko131** [comment]
@pepijnve 
Sorry i edited my comment above!

But the result is the same the inputstrean that i obtain is empty...

**Comment by fiasko131** [comment]
In addition, I just realized that it erases the bytes of the open file. The files I tested have a size 0 !!?

**Comment by pepijnve** [comment]
@hierynomus agreed. it would make sense if Java supported explicit default parameter values. Since that's not the case interpreting null as supersede probably violates the least surprise principal. Better to simply throw NPE or IAE. That probably applies to all the parameters except for the Set params. There equating null with an empty set is probably not all that surprising.

**Comment by fiasko131** [comment]
@hierynomus 
ok it works with SMB2CreateDisposition.FILE_OPEN parameter.
Thanks

**Comment by timomeinen** [comment]
Uff - by using a null value for the SMB2CreateDisposition will empty out the source file. That is a killer. :-(
