### ISSUE TITLE
Is this library supported on Android?

### ISSUE THREAD

**Issue by HubKing** [hierynomus/smbj#42]
I could not find any example, so I just guessed how it would work, and wrote the following code.

	SMBClient client = new SMBClient();
	Log.d(TAG, "Trying to connect");
	Connection conn = client.connect(ServerIP);
	AuthenticationContext auth = new AuthenticationContext(ID, Password.toCharArray(), null);
	Log.d(TAG, "Trying to authenticate");
	Session ses = conn.authenticate(auth);

But `authenticate()` threw an exception.

    com.hierynomus.ntlm.NtlmException: java.security.NoSuchAlgorithmException: no such algorithm: MD4 for provider BC

Did I do something wrong, or is this library not supported on Android?

**Comment by hierynomus** [comment]
It should not be too hard to support Android. I will look into it. Thanks
for asking!

Op 2 apr. 2017 12:00 schreef "GitHub King" <notifications@github.com>:

I could not find any example, so I just guessed how it would work, and
wrote the following code.

SMBClient client = new SMBClient();
Log.d(TAG, "Trying to connect");
Connection conn = client.connect(ServerIP);
AuthenticationContext auth = new AuthenticationContext(ID,
Password.toCharArray(), null);
Log.d(TAG, "Trying to authenticate");
Session ses = conn.authenticate(auth);

But authenticate() throwed an exception.

com.hierynomus.ntlm.NtlmException:
java.security.NoSuchAlgorithmException: no such algorithm: MD4 for
provider BC

Did I do something wrong, or is this library not supported on Android?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/hierynomus/smbj/issues/42>, or mute the thread

**Comment by zuoshui** [comment]
Hi hierynomus,
I use this demo to list, it return NT Status: STATUS_ACCESS_DENIED (0xc0000022)


32	7.305456	192.168.1.110	192.168.1.10	SMB2	156	Find Request File:  SMB2_FIND_ID_BOTH_DIRECTORY_INFO Pattern: *

33	7.308874	192.168.1.10	192.168.1.110	SMB2	131	Find Response, Error: STATUS_ACCESS_DENIED

what the reason? @hierynomus

**Comment by hierynomus** [comment]
It most probably got to do with signatures being not sent. Can you give it a try with the current master?

**Comment by hierynomus** [comment]
@HubKing This should be fixed with the next release with the introduction of our own abstraction over SecurityProvider (b01ac77917c0cc9f0a7ddf8d32c6d40192f858bf). You could try building the latest master in order to verify whether this fixes it.

**Comment by hierynomus** [comment]
@HubKing Have you tried building a recent master version to check whether it works on Android?

**Comment by hierynomus** [comment]
Released 0.1.0 which contains these fixes, closing the issue
