### ISSUE TITLE
Support for SMB1?

### ISSUE THREAD

**Issue by umangsamani** [hierynomus/smbj#513]
In order to provide backward compatibility, does smbj be used to connect to smbv1 enabled shares ?
Reason for asking this is : I tried to use the test code to connect to SMB2 enabled share, and I am able to get the list of files inside a directory.
But when I try to do the same on SMB1 enabled share, I getting an exception which says : STATUS_BAD_NETWORK_NAME

**Comment by hierynomus** [comment]
Hi @umangsamani, Currently there is no support for SMBv1. And as it is a deprecated and broken protocol, it is not high on the feature list as you can imagine. What you can do to provide better error support is to set `SmbConfig.withMultiProtocolNegotiate(true)`. This will throw an `SMB1NotSupportedException` if the server enforces SMB1.

**Comment by hierynomus** [comment]
Are you sure you've set all the parameters correctly? `STATUS_BAD_NETWORK_NAME` typically means the path could not be found.

Can you post teh entire stacktrace? And maybe some logging?

**Comment by umangsamani** [comment]
![image](https://user-images.githubusercontent.com/26565744/71185339-44593f00-22a1-11ea-9375-0bcb677302ba.png)
In continuation to the previous query, I have now set `SmbConfig.withMultiProtocolNegotiate(true)` , but still I am able to connect to the share. Above image shows that SMB1 is enabled.
Below are the logs :

[main] INFO com.hierynomus.smbj.connection.Connection - Successfully connected to: x.x.x.x
[main] INFO com.hierynomus.smbj.connection.Connection - Successfully authenticated administrator on x.x.x.x, session is 255123464753013
[main] INFO com.hierynomus.smbj.session.Session - Connecting to \\x.x.x.x\D$ on session 255086764753013

I want it to fail, when the connecting server have SMB1 enabled.

**Comment by ecki** [comment]
Hello,

The negotiation will pick the highest protocol available, so it will only fail of the server has only smb1 available (since smbj does not). It will pick smb2+ on any more recent server.

BTW You can see if the server offers smb2/3 with Get-SmbServerConfiguration | Select EnableSMB2Protocol


--
https://Bernd.eckenfels.net

________________________________
Von: umangsamani <notifications@github.com>
Gesendet: Donnerstag, Dezember 19, 2019 4:24 PM
An: hierynomus/smbj
Cc: Subscribed
Betreff: Re: [hierynomus/smbj] Support for SMB1? (#513)


[image]<https://user-images.githubusercontent.com/26565744/71185339-44593f00-22a1-11ea-9375-0bcb677302ba.png>
In continuation to the previous query, I have now set SmbConfig.withMultiProtocolNegotiate(true) , but still I am able to connect to the share. Above image shows that SMB1 is enabled.
Below are the logs :

[main] INFO com.hierynomus.smbj.connection.Connection - Successfully connected to: x.x.x.x
[main] INFO com.hierynomus.smbj.connection.Connection - Successfully authenticated administrator on x.x.x.x, session is 255123464753013
[main] INFO com.hierynomus.smbj.session.Session - Connecting to \x.x.x.x\D$ on session 255086764753013

I want it to fail, when the connecting server have SMB1 enabled.

**Comment by umangsamani** [comment]
![image](https://user-images.githubusercontent.com/26565744/71188166-791bc500-22a6-11ea-8934-f0df3f047a0a.png)

**Comment by umangsamani** [comment]
On a different note, if I want to connect to localhost, and need to list local drives; can it be done? Because the code which I am writing is generic, if the user has entered the servername and share name, I will connect to it and will show the directories, and if user hasn't entered any thing; it means I am connecting to local drives.

If required, I can create a new issue for it,

**Comment by ecki** [comment]
You can connect to localhost (if the host allows it), however it is of course faster and more feature rich (showing non-shared drives) if you access the Filesystem locally.

You cannot list shares with smbj.


--
http://bernd.eckenfels.net

________________________________
Von: umangsamani <notifications@github.com>
Gesendet: Freitag, Dezember 20, 2019 10:47 AM
An: hierynomus/smbj
Cc: Bernd; Comment
Betreff: Re: [hierynomus/smbj] Support for SMB1? (#513)


On a different note, if I want to connect to localhost, and need to list local drives; can it be done? Because the code which I am writing is generic, if the user has entered the servername and share name, I will connect to it and will show the directories, and if user hasn't entered any thing; it means I am connecting to local drives.

If required, I can create a new issue for it,

**Comment by hierynomus** [comment]
Closing this issue, as the SMB1 question has been answered.
